### ISSUE TITLE
Language and place Location unavailable before 07-2020

### ISSUE THREAD

**Issue by SelimBS** [thepanacealab/covid19_twitter#14]
Hello, It seems that the language and place location are not present in the datasets before July 2020. It was my understanding that they were added to all tweets in version 20. 
I was wondering if I misunderstood and they were added to new tweets scraped from version 20 or is this a mistake?

Thank you for your amazing dataset and work :)

**Comment by jmbanda** [comment]
Greetings,

The dailies do not have that information as you mention, however, if you look at the full_dataset.gz or the full_dataset-clean.gz files in the Zenodo repository, all tweets have that information there.  We re-processed the early tweets when we introduced that change, but didn't update the dailies due to time constraints.
