### ISSUE TITLE
Lack of some data in the full clean dataset

### ISSUE THREAD

**Issue by fatadel** [thepanacealab/covid19_twitter#6]
In my understanding, the set of tweet ids from `clean_language_en.tsv` should be a proper subset of the set of tweet ids from `full_dataset_clean.tsv`. However, it is not the case - some ids are not presented in the full clean dataset. So, I am wondering how and why this happens. I can provide a list of non-presented tweets if needed.
Thanks in advance!

**Comment by jmbanda** [comment]
Interesting comment. We were not aware of it and will look into it. It might be that the tweet is empty (or just a link to an image). However, if you can provide some of those ids, it would be great for us to look at them. Thanks!

P.S. On version 20, we will change our release format to be more streamlined and include language and location data within the actual full dataset files (rather than separately) so it will be great to fix this issue in advace!

**Comment by fatadel** [comment]
Here is an exhaustive list of those ids - 
[not_presented.zip](https://github.com/thepanacealab/covid19_twitter/files/4943702/not_presented.zip).

**Comment by jmbanda** [comment]
Thanks, that is a decent amount. Interestingly it is up until 5/19 only. Are you only using data until then? or the problem does not happen with later tweets?

**Comment by fatadel** [comment]
We used the 16th version of the dataset, so the data is until the 27th of June. So, apparently the problem doesn't appear with the later tweets.

**Comment by jmbanda** [comment]
Thanks for finding this bug, we have fixed this on version 20 (https://zenodo.org/record/3960911)
